### ISSUE TITLE
Fedora container can't run dnf updateinfo

### ISSUE THREAD

**Issue by jaryan-rh** [openshift-instruqt/instruqt#165] opened 2022-11-10 15:20 UTC
**In which track did this bug occur?**

Understanding Subsystems / Understanding registries

**what is the url for the track?**
https://developers.redhat.com/courses/subsystems/registries

**At what step of the track did this happen?**

Evaluating Trust - Images and Registry Servers

```
podman run -it registry.fedoraproject.org/fedora dnf updateinfo
```

**Describe the bug**

**Logs or error messages**
```[root@crc-dzk9v-master-0 /]# podman run -it registry.fedoraproject.org/fedora dnf updateinfo
Fedora 36 - x86 0.0  B/s |   0  B     00:00
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-36&arch=x86_64&countme=1 [getaddrinfo() thread failed to start]
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-36&arch=x86_64 [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-36&arch=x86_64 [getaddrinfo() thread failed to start]
```

**Expected behavior**
dnf updateinfo complete successfully

**Screenshots**
See code copy and pase above

**Desktop (please complete the following information):**
 - OS: MacOS 12.6
 - Browser Chrome
 - Version 107.0.5304.87

**Additional context**
Looks like proxy issue from the CoreOS node, previous version of this lab ran directly on a CentOS or RHEL server.

**Comment by jaryan-rh** [comment] 2022-11-10 15:21
Expected output of the fedora container

```
Updates Information Summary: available
    1 Security notice(s)
        1 Low Security notice(s)
    1 Bugfix notice(s)
    2 Enhancement notice(s)
    1 other notice(s)
```

**Comment by cedricclyburn** [comment] 2023-01-06 00:03
Hello @jaryan-rh, the VM may have been functioning strangely, but it looks like it's back to expected behavior. This may have been due to our migration of labs the past few months. Closing for now!
<img width="479" alt="image" src="https://user-images.githubusercontent.com/54345140/210902966-62da5068-05dd-43e9-affc-1a94d9e6c7d8.png">

**Closed as completed by cedricclyburn** 2023-01-06 00:03 UTC
Labels: bug
