### ISSUE TITLE
BUG: missing/broken images in developing-on-openshift/deploying-python

### ISSUE THREAD

**Issue by ryanj** [openshift-instruqt/instruqt#170] opened 2022-11-17 19:15 UTC
**In which track did this bug occur?**
[Deploying Applications From Source](https://play.instruqt.com/openshift/tracks/deploying-applications-from-source)

Name the instruqt track that you were using
Deploying Applications From Source developing-on-openshift/deploying-python

**what is the url for the track?**
https://play.instruqt.com/openshift/tracks/deploying-applications-from-source

**At what step of the track did this happen?**
2-n

If you can't remember the exact step, try to explain where in the track did the bug happen

**Describe the bug**
images did not load correctly.  Broken jpeg image shown instead.

**Expected behavior**
The content was difficult to follow because the images were missing

**Comment by cedricclyburn** [comment] 2023-01-05 23:47
Looks like this was a duplicate of the [original track](https://play.instruqt.com/openshift/tracks/using-the-cluster-deploying-python), which I confirmed all images are loading correctly

**Closed as completed by cedricclyburn** 2023-01-05 23:47 UTC
Labels: bug
